INSERT INTO "USERS" (NAME,EMAIL,AGE,USERNAME,PASS,ROLE) VALUES ('GUTS','edgar.espinoza@infosys.com',20,'user','user','USER');
INSERT INTO "USERS" (NAME,EMAIL,AGE,USERNAME,PASS,ROLE) VALUES ('edgar','edgar.espinoza@infosys.com',42,'admin','admin','LIBRARIAN');

INSERT INTO BOOK (AUTHOR,GENRE,TITLE,STATUS) VALUES ('LOVECRAFT','HORROR','CALL OF CTHULHU','AVAILABLE');
INSERT INTO BOOK (AUTHOR,GENRE,TITLE,STATUS) VALUES ('j.Peterson','SELF_HELP','Twelve rules for','AVAILABLE');


