CREATE TABLE BOOK (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AUTHOR VARCHAR(50) NOT NULL,
    GENRE VARCHAR(50) NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(10) NOT NULL
);

CREATE TABLE "USERS" (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(12) NOT NULL UNIQUE,
    PASS VARCHAR(12) NOT NULL,
    AGE INT NOT NULL,
    ROLE VARCHAR(12)
);

CREATE TABLE USERS_BOOK (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    BOOK_ID BIGINT NOT NULL,
    BORROW_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RETURN_DATE TIMESTAMP NULL,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY(BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_unique_user_book ON USERS_BOOK(USER_ID, BOOK_ID);
